### ISSUE TITLE
Option to generate config for running FireFly core outside docker compose

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger-labs/firefly-cli#39] opened 2021-06-15 12:49 UTC
For developers working on core, it would be handy to have a mode that generates the YAML files for running core outside of docker-compose using the exposed ports.

This is a manual activity today, that has to be re-done each time on the `ff remove` / `ff init` cycle:
- `ff init` / `ff start -n`
- Edit `docker-compose.yml` to comment out one or more `firefly_core_0` services
- Edit `firefly_1.core` etc. to change all the docker link hostnames, into `localhost:510x` hostnames
- `ff stop` / `ff start`
- Run FireFly core (using VSCode `launch.json` etc)

**Comment by nguyer** [comment] 2021-06-15 19:08
While not exactly a duplicate of https://github.com/hyperledger-labs/firefly-cli/issues/2, there is a lot of overlap here. It's a good idea.

**Comment by nguyer** [comment] 2021-06-16 16:04
@peterbroadhurst How do you think node/org registration should work in this case? I'm guessing running the firefly node outside docker will be a manual command because the CLI won't know where the `firefly` binary is that you want to run (and you may need to recompile/rerun many times during testing). When running in this mode, should we just skip the `runFirstTimeSetup()`?

**Comment by peterbroadhurst** [comment] 2021-06-17 12:29
Great point... I guess with the manual process today we let everything init first then do the manual editing on the yaml.

So we could definitely just skip the registration step, but then you've still got manual stuff to do, so I'm wondering if we've made things better.
Or we could have a separate command to re-write the config as external, after you've done the initial `ff start` (not sure what that command would be though(.
Or we could decide it's not worth doing anything right now, and the process as it is today isn't too bad, and we could be in danger of over complicating the `ff` tool for something outside it's core purpose 🤷

**Closed** 2021-07-30 19:44 UTC
Labels: enhancement
